spring:
  datasource:
    url: jdbc:mysql://mysql-container:3306/doctorforuDB
    username: root
    password: Doctor119!

EasyResponse:
  service:
    url: http://127.0.0.1:8080

api:
  access:
    token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJEb2N0b3JGb3JVIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTcxOTQwMzM1N30.umlRwi9dUJctmt397zlFi6pdC_VASCDPUJie24KrEYqO3p1S3v9zZT4-umw4LsgifIopxoyY4u5D7NR7_6oeyw
