spring:
  datasource:
    url: jdbc:mysql://211.34.229.173:3306/doctorforuDB?serverTimezone=Asia/Seoul
    username: mysql
    password: Doctor119!

EasyResponse:
  service:
    url: http://127.0.0.1:8080

api:
  access:
    token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJEb2N0b3JGb3JVIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTcxOTIzNTYzNH0.tzFPXVfLK2OCA4EXgLt_z3BvFaGPNLjnTC6QyIveXMj7Ow4PiYfnvW47S0nBBsh7pwlFUVhjNP-NpvD_xbkomw
