spring:
  datasource:
    url: jdbc:mysql://doctorforudb.czmk2m0y4uvc.us-east-1.rds.amazonaws.com:3306/doctorforuDB
    username: doctor
    password: Doctor119!

EasyResponse:
  service:
    url: http://eureka-container:8888

api:
  access:
    token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJEb2N0b3JGb3JVIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTcxODM1MTgyMH0.FKtwQzlYsTwBKv-i4d3Ko26NLvH8gtmu2kSRrPhs2McUT_Rqk6Ot1K4wnJ6ztxav3flJDrzKD97KBRXWS7b3Yw
