spring:
  datasource:
    url: jdbc:mysql://211.34.229.173:3306/doctorforuDB?serverTimezone=Asia/Seoul
    username: mysql
    password: Doctor119!

EasyResponse:
  service:
    url: http://127.0.0.1:8080

api:
  access:
    token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJEb2N0b3JGb3JVIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTcxOTE2NTUwMn0.x4RVOgXREsxJ8Lkphf3I4zHX03qYQw0yGfcbd1Qtwj4nk5kDtbpRRJ6If6agObW1iP3mmOO9kaP5iQYD7ouwxg
