spring:
  datasource:
    url: jdbc:mysql://doctorforudb.czmk2m0y4uvc.us-east-1.rds.amazonaws.com:3306/doctorforuDB
    username: doctor
    password: Doctor119!

EasyResponse:
  service:
    url: http://config-container:8888

api:
  access:
    token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJEb2N0b3JGb3JVIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTcxOTQwMzM1N30.umlRwi9dUJctmt397zlFi6pdC_VASCDPUJie24KrEYqO3p1S3v9zZT4-umw4LsgifIopxoyY4u5D7NR7_6oeyw
