spring:
  datasource:
    url: jdbc:mysql://doctorforudb.czmk2m0y4uvc.us-east-1.rds.amazonaws.com:3306/doctorforuDB
    username: doctor
    password: Doctor119!

  mail:
    username: uj0791navercom@skuniv.ac.kr
    password: zrui etaf buvz vuig

jwt:
  secret: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd6eXoxMjMxMjMxMjMxMjMxMjMxMzEyMzEyMzEzMTIzMTIzMTIzMTMxMjMxMzEzMTMxMjM
  redis:
    host: easycluster.rxybdx.ng.0001.apn2.cache.amazonaws.com
    port: 6379
