spring:
  datasource:
    url: jdbc:mysql://mysql-container:3306/doctorforuDB
    username: root
    password: Doctor119!

  mail:
    username: uj0791navercom@skuniv.ac.kr
    password: zrui etaf buvz vuig

jwt:
  secret: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd6eXoxMjMxMjMxMjMxMjMxMjMxMzEyMzEyMzEzMTIzMTIzMTIzMTMxMjMxMzEzMTMxMjM
  redis:
    host: easycluster.rxybdx.ng.0001.apn2.cache.amazonaws.com
    port: 6379
